trash
Athameon/wbs_group_project_week_3 pull request #4
Opened 2021-05-12 17:49 UTC by Joachim0211

Ben, sorry I missed you. This is just a small step but seems to work.
Joachim

2021-05-13 11:44 UTC, Athameon requested changes

2021-05-13 11:44 UTC, Athameon commented on script.js
> +    const trash = document.querySelector(`#${id}`);
You don't need the id for this task.
Skip the id of line 22 and call the variable of the line direct trash.

2021-05-14 09:27 UTC, Joachim0211 commented
I shortened it accordingly. Joachim

2021-05-14 10:12 UTC, Athameon approved these changes
ok

2021-05-14 10:12 UTC, merged